### ISSUE TITLE
Allow bit2core to embed helper files in .COR files

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-tools#105]
When a user puts a new SD card into a MEGA65 and wishes to format it, there are several files that should get copied on, but that are too large to fit in the bitstream.  But the flash slots on the MEGA65R3 are 8MB, which is about 2MB larger than the typical compressed bitstream for the MEGA65R3.  This means that we can make creative use of the slack space in flash slot 0 to stash these helpful files.  We can then modify FDISK/FORMAT to write those files out onto the SD card. Alternatively we could teach the freezer and HYPPO to know to load the freeze menu from the flash memory if there is no FREEZER.M65 on the SD card.

The first step in any case, is to allow bit2core to embed files into the slack space.

**Comment by lydon42** [comment]
This works and is used in the release COR.
There are also the additional prepare.sh and bitembed scripts in mega65-core/release-build to support Jenkins in generating those "loaded" COR files.
