### ISSUE TITLE
m65 tool does not use the correct palette to take screen shots

### ISSUE THREAD

**Issue by M3wP** [MEGA65/mega65-tools#109]
When taking the screen shot, m65 tool needs to save the currently mapped palette and then map in the correct palette before doing the screen shot.  When complete, the original mapping should be restored.

**Comment by lydon42** [comment]
In the example program the MAPEDPAL is 01, but BTPALSEL is 11. So screenshot gets palette 01 from mapped memory, but VIC is actually drawing from palette 11.

**Comment by lydon42** [comment]
Switching MAPEDPAL to BTPALSEL before fetchign palette does fix the problem.
