### ISSUE TITLE
Add a Refresh option to take into account newly inserted sdcard

### ISSUE THREAD

**Issue by eliyo** [MEGA65/mega65-tools#114]
It seems the sdcard in external slot needs to be inserted before entering the disk formating tool. Using a Refresh option we could insert the card after the tool is run and it would detect it.

**Comment by lydon42** [comment]
Disk formatting tool is not part of mega65-tools but mega65-fdisk.

But yes, all external SD Card Stuff is clunky, and will be hopefully fixed by the new SD Card code coming soon.

HYPPO needs to be changed (i.e. mega65-core) to make better SD Card handling.
