### ISSUE TITLE
Explicitly tell which card slot is about to be formatted

### ISSUE THREAD

**Issue by eliyo** [MEGA65/mega65-tools#115]
In the disk formatting tool, after selecting a card slot to format, we are asked to type DELETE EVERYTHING but there is no clear information on screen about which slot will be used. So if we are not sure we typed the right value (0 or 1), we're in doubt. Please add a message explicitly mentioning in which slot the formatting will take place.

**Comment by lydon42** [comment]
this is the wrong repository, should be mega65-fdisk.
