### ISSUE TITLE
merge m65dbg into mega65-tools

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-tools#131]
m65dbg and mega65-tools share a very common code base. Merging them and reusing all the common components reduces maintenance work and cross-project bug fixing.

**Comment by lydon42** [comment]
First step of the merge done by @dansanderson in #132

**Comment by dansanderson** [comment]
m65dbg is now mostly functional in MEGA65:mega65-tools/merge2-m65dbg. I have explicitly disabled the type (tt) and FTP (ftp) commands while we figure out how to best refactor that code. I'll create separate issues for those. Resolving this one.
