### ISSUE TITLE
mega65_ftp putslot command to install freeze slots saved with getslot

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-tools#153]
It would be cool to be able to extract freeze states from an SD card as files, and install freeze files into slots.

mega65_ftp has a `getslot` command to download a freeze slot. Apparently there isn't a `putslot` yet, so this issue requests one.

**Comment by gurcei** [comment]
Ah yep, `putslot <slot> <source name>` command is now available. Can't recall which commit it was that added this, but think it was from a few months back.
