### ISSUE TITLE
M65: PRG load after ROM load fails

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-tools#2]
After loading ROM 910523.bin by m65, any loaded PRG file intended for C65-mode, stalls with this output:

```
m65 -l COM9 -R 910523.bin
m65 -l COM9 -r "Turbo Disk 65 v3.prg"
...
[T+0sec] Detecting C64/C65 mode status.
[T+2sec] Could not determine C64/C65/MEGA65 mode.
[T+2sec] Loading file '/.../.../Turbo Disk 65 v3.prg'
[T+3sec] CPU in C65 BASIC 10 main loop.
[T+3sec] Injecting string into key buffer at $02B0 : DLo"![$0d]
[T+3sec] Waiting for breakpoint at $F664 to trigger.
```

NOTE: This issue only occurs in C65-mode. I.e., loading a c64 .prg via `m65 -l COM9 -4r commando.prg` still works.

It looks like m65 has a problem to evaluate the MEGA65 mode after loading a ROM file. 

Loading a PRG file with RESET option works but that of course removes the ROM file.

But loading a PRG after 911001.bin works (also several times).

**Comment by Taygair** [comment]
Might be related to this case which belongs here: https://github.com/MEGA65/m65connect/issues/6

**Comment by gurcei** [comment]
I've confirmed that Paul's recent changes have fixed this issue.
