### ISSUE TITLE
Building mega65_ftp with CC65 V2.19 bc8cca9 error

### ISSUE THREAD

**Issue by hernandp** [MEGA65/mega65-tools#47]
With cc65.exe V2.19 - Git bc8cca9 you will get the following error when executing `make`.  I'm using mega65_ftp but could be a general issue.
```
$ make USE_LOCAL_CC65=1 bin/mega65_ftp.exe
git submodule init
git submodule update
cl65 --config src/tests/vicii.cfg -I src/mega65-libc/cc65/include -O -o src/utilities/remotesd.prg --mapfile src/utilities/remotesd.map src/utilities/remotesd.c  src/mega65-libc/cc65/src/*.c src/mega65-libc/cc65/src/*.s
1 errors and 0 warnings generated.
src/mega65-libc/cc65/src/conio.c(499): Error: Conflicting function types for 'cputcxy'
make: *** [Makefile:229: src/utilities/remotesd.prg] Error 1

```

This is already fixed at libc, so we need to update cc65 submodule  to latest (see https://github.com/MEGA65/mega65-libc/commit/068898d56e163cf9eef54f3dbee42e11decbf82d)

**Comment by gurcei** [comment]
Ok, I'm going to move it to an even newer commit:

https://github.com/MEGA65/mega65-libc/commit/a172d1b0ba1c93e9489399334b2631d869d88cbf
