### ISSUE TITLE
m65 doesn't support two-digit COM-ports

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-tools#48]
Reported by jesperrula on M65Connect

When setting the m65 to COM port 10 or higher, m65connect will return a "file not found" error when issuing any command.
-> After testing it the problem seems to be caused by m65

**Comment by TheChief** [comment]
Please have a look at this link: https://support.microsoft.com/en-us/topic/howto-specify-serial-ports-larger-than-com9-db9078a5-b7b6-bf00-240f-f749ebfd913e

This should provide you the solution to get rid of this bug.

**Comment by gardners** [comment]
Fixed in the above commit.
