### ISSUE TITLE
ROMDIFF: Compiler warnings SNPRINTF overflow

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-tools#55]
17:02 1076 /Users/home/MEGA65/C65/tools cc -o romdiff romdiff.c
romdiff.c:369:3: warning: 'snprintf' will always overflow; destination buffer has size 224, but size argument is 256 [-Wbuiltin-memcpy-chk-size]
  snprintf((char*)&header[32], 256, "%s", normalise(argv[1]));
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
romdiff.c:370:3: warning: 'snprintf' will always overflow; destination buffer has size 160, but size argument is 256 [-Wbuiltin-memcpy-chk-size]
  snprintf((char*)&header[32 + 64], 256, "%s", normalise(argv[2]));
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
2 warnings generated.

**Comment by lydon42** [comment]
Fixed in d373f4c0510f6d9a2c8714cb0516dee7bc650a09
