### ISSUE TITLE
GENERAL: Enhancing MEGA65 Tool 'README.md' page

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-tools#73]
It would be nice to see the MEGA65 Tool up to date:
- Main page: romdiff and m65dbg mentioned aside of the existing one (maybe also others I'm not aware of
- A link to the builds on CI Tools page on the main page (possible to show publish date on CI Tools)
- All latest version of available CI Tools

**Comment by gurcei** [comment]
Things are looking a bit better on this front:
* The CI-latest page is looking a lot presentable and tidier now
* I made a mention of romdiff there too now, though m65dbg will have to wait until it migrates into this repo (presently, it is housed within its own repo)
* The `mega65-tools` repo's README.md now has a 'Download' section that provides a link to the 'CI-latest' page.

Thinking it's ok to close this ticket now, and we can refine things further as we go.
