### ISSUE TITLE
Exominer is not in the make file

### ISSUE THREAD

**Issue by manavarora821** [MEGA65/mega65-tools#79]
We can add the Examiner file in the makefile that will help to improve the build process.

**Comment by gurcei** [comment]
Oh, the exomizer tool is getting used by the mega65-core repo, and already has a few cards in relation to this topic:
- https://github.com/MEGA65/mega65-core/issues?q=is%3Aissue+exomizer+

As the exomizer isn't used within mega65-tools, I'll close this ticket here, and suggest keeping tabs on the tickets still open in mega65-core repo on this matter
