### ISSUE TITLE
mega65_ftp issue

### ISSUE THREAD

**Issue by amar0039** [MEGA65/mega65-tools#80]
![mega65-tools](https://user-images.githubusercontent.com/73209262/122674146-fc5b0580-d212-11eb-8aea-88e34ac20563.jpeg)

**Comment by gurcei** [comment]
From the build output you've given, the build appears to have been successful. Take a look in the bin folder and you should find your "mega65_ftp" binary to run

**Comment by gurcei** [comment]
Feel like the situation has been explained, so closing the card.
