### ISSUE TITLE
Cannot Find -lncurses

### ISSUE THREAD

**Issue by manavarora821** [MEGA65/mega65-tools#81]
![33_t](https://user-images.githubusercontent.com/64771425/122674155-02e97d00-d213-11eb-8316-58ccf28ca32e.png)

**Comment by gurcei** [comment]
Take a look at the "building under linux" steps here:

https://github.com/MEGA65/mega65-tools

I believe the pre-req you are missing is mentioned there (libncurses5-dev)

**Comment by gurcei** [comment]
Feel like the situation has been explained now, so closing the card.
