### ISSUE TITLE
M65: Sending prg file doesn't work anymore

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-tools#88]
Majikeyric reported this one in "closed-roms":

With the 920217 ROM m65 doesn't work anymore to inject PRG (920215 ROM works). Maybe it's normal in current state?

command line : m65 -l com6 -F -r test.prg

![unknown](https://user-images.githubusercontent.com/21134000/130048044-6ab5dbf5-d287-44be-aaf4-687b781ad4ab.png)

**Comment by Taygair** [comment]
Might me similar to this one: https://github.com/MEGA65/mega65-tools/issues/2

**Comment by gardners** [comment]
Works fine for me from under Linux.
Is it a Windows-specific problem perhaps?
![mega65-screen-000001](https://user-images.githubusercontent.com/665423/130050715-5e27389f-b568-40be-8735-b4e0e715b11c.png)

(Note that the for the image above it was a C64 program I loaded, thus why it didn't run. But you can see that there was no FILE NOT FOUND error)

Are you using the latest m65 binary?

**Comment by Taygair** [comment]
Tested on Mac to real hardware (R2), works also here:
- 920217.BIN
- mega65r2-dev.bit (V116)
-> Loaded with alpaca.prg

**Comment by Majikeyric** [comment]
I use Windows 7.
M65 version : 20210525.08-HEAD_n-713db01
bitstream : 116-0fb485d

**Comment by Majikeyric** [comment]
I updated M65 to the latest version (20210727) and I have the same issue.

**Comment by Majikeyric** [comment]
With latest BS ROM (920219), it works again.

**Comment by Taygair** [comment]
Excellent and thank you Paul!
