### ISSUE TITLE
Auto upper-case any `put` of .d81 files

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-tools#92]
Just to avoid user frustration at their lower-case .d81 files not mounting properly.

**Comment by gurcei** [comment]
This might already be the case now that the vfat/lfn logic is in place (which prefers to leave the 8.3 names all uppercase). I will try confirm this later.

**Comment by lydon42** [comment]
LFN support is there. Auto upper-case is a bad thing, as the user might not know that it happened (no, users don't read messages form the program, ever).
