### ISSUE TITLE
Missing usage in help

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-tools#96]
As Bitshifters romdiff.c code for Mac OSX is working I guess it will be taken over. From 

The "old" romdiff.osx that was not working, showed this help:
usage: romdiff <reference ROM> <new ROM> <output file>
       **romdiff <rom diff file> <outputfile>**

Bitshifters version only shows this:
usage: romdiff <reference ROM> <new ROM> <output file>

So the new version is not telling how to **patch a file** (second line) which should be added in case you take over Bitshifters code.

**Comment by lydon42** [comment]
Added in d373f4c0510f6d9a2c8714cb0516dee7bc650a09
